// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

package web

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Handler struct {
	// Types that are valid to be assigned to Pattern:
	//	*Handler_Get
	//	*Handler_Put
	//	*Handler_Post
	//	*Handler_Delete
	//	*Handler_Patch
	Pattern              isHandler_Pattern `protobuf_oneof:"pattern"`
	Title                string            `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description          string            `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Parameters           []*Parameter      `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{0}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

type isHandler_Pattern interface {
	isHandler_Pattern()
}

type Handler_Get struct {
	Get string `protobuf:"bytes,1,opt,name=get,proto3,oneof"`
}

type Handler_Put struct {
	Put string `protobuf:"bytes,2,opt,name=put,proto3,oneof"`
}

type Handler_Post struct {
	Post string `protobuf:"bytes,3,opt,name=post,proto3,oneof"`
}

type Handler_Delete struct {
	Delete string `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

type Handler_Patch struct {
	Patch string `protobuf:"bytes,5,opt,name=patch,proto3,oneof"`
}

func (*Handler_Get) isHandler_Pattern() {}

func (*Handler_Put) isHandler_Pattern() {}

func (*Handler_Post) isHandler_Pattern() {}

func (*Handler_Delete) isHandler_Pattern() {}

func (*Handler_Patch) isHandler_Pattern() {}

func (m *Handler) GetPattern() isHandler_Pattern {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Handler) GetGet() string {
	if x, ok := m.GetPattern().(*Handler_Get); ok {
		return x.Get
	}
	return ""
}

func (m *Handler) GetPut() string {
	if x, ok := m.GetPattern().(*Handler_Put); ok {
		return x.Put
	}
	return ""
}

func (m *Handler) GetPost() string {
	if x, ok := m.GetPattern().(*Handler_Post); ok {
		return x.Post
	}
	return ""
}

func (m *Handler) GetDelete() string {
	if x, ok := m.GetPattern().(*Handler_Delete); ok {
		return x.Delete
	}
	return ""
}

func (m *Handler) GetPatch() string {
	if x, ok := m.GetPattern().(*Handler_Patch); ok {
		return x.Patch
	}
	return ""
}

func (m *Handler) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Handler) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Handler) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Handler) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Handler_Get)(nil),
		(*Handler_Put)(nil),
		(*Handler_Post)(nil),
		(*Handler_Delete)(nil),
		(*Handler_Patch)(nil),
	}
}

type Parameter struct {
	// Types that are valid to be assigned to Description:
	//	*Parameter_Path
	//	*Parameter_Body
	Description          isParameter_Description `protobuf_oneof:"description"`
	Name                 string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_461bb3ac99194e85, []int{1}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

type isParameter_Description interface {
	isParameter_Description()
}

type Parameter_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type Parameter_Body struct {
	Body string `protobuf:"bytes,2,opt,name=body,proto3,oneof"`
}

func (*Parameter_Path) isParameter_Description() {}

func (*Parameter_Body) isParameter_Description() {}

func (m *Parameter) GetDescription() isParameter_Description {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Parameter) GetPath() string {
	if x, ok := m.GetDescription().(*Parameter_Path); ok {
		return x.Path
	}
	return ""
}

func (m *Parameter) GetBody() string {
	if x, ok := m.GetDescription().(*Parameter_Body); ok {
		return x.Body
	}
	return ""
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Parameter_Path)(nil),
		(*Parameter_Body)(nil),
	}
}

var E_Handler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*Handler)(nil),
	Field:         51788,
	Name:          "web.handler",
	Tag:           "bytes,51788,opt,name=handler",
	Filename:      "web.proto",
}

func init() {
	proto.RegisterType((*Handler)(nil), "web.Handler")
	proto.RegisterType((*Parameter)(nil), "web.Parameter")
	proto.RegisterExtension(E_Handler)
}

func init() {
	proto.RegisterFile("web.proto", fileDescriptor_461bb3ac99194e85)
}

var fileDescriptor_461bb3ac99194e85 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3f, 0x4e, 0xec, 0x30,
	0x10, 0x87, 0x5f, 0x5e, 0xfe, 0x91, 0x09, 0x20, 0x64, 0xad, 0x90, 0x45, 0x81, 0xa2, 0xad, 0xb6,
	0x4a, 0xb1, 0x74, 0x94, 0x5b, 0xa5, 0x41, 0xa0, 0x94, 0x74, 0xce, 0x66, 0x48, 0x22, 0x65, 0x63,
	0xcb, 0x99, 0x68, 0xc5, 0x3d, 0x38, 0x16, 0x47, 0xe1, 0x10, 0xc8, 0x8e, 0x13, 0x2d, 0x9d, 0xbf,
	0x6f, 0x66, 0xac, 0xf9, 0x0d, 0x24, 0x67, 0xac, 0x72, 0xa5, 0x25, 0x49, 0xe6, 0x9f, 0xb1, 0x7a,
	0xb8, 0xab, 0x71, 0x3c, 0xea, 0x4e, 0x91, 0xd4, 0xb3, 0xde, 0xfe, 0x78, 0x10, 0x17, 0x62, 0xa8,
	0x7b, 0xd4, 0x8c, 0x81, 0xdf, 0x20, 0x71, 0x2f, 0xf3, 0x76, 0x49, 0xf1, 0xaf, 0x34, 0x60, 0x9c,
	0x9a, 0x88, 0xff, 0x5f, 0x9c, 0x9a, 0x88, 0x6d, 0x20, 0x50, 0x72, 0x24, 0xee, 0x3b, 0x69, 0x89,
	0x71, 0x88, 0x6a, 0xec, 0x91, 0x90, 0x07, 0xce, 0x3b, 0x66, 0xf7, 0x10, 0x2a, 0x41, 0xc7, 0x96,
	0x87, 0xae, 0x30, 0x23, 0xdb, 0x40, 0x48, 0x1d, 0xf5, 0xc8, 0x23, 0xe3, 0xcb, 0x19, 0x58, 0x06,
	0xe9, 0xb2, 0x65, 0x27, 0x07, 0x1e, 0xdb, 0xda, 0xa5, 0x62, 0x39, 0x80, 0x12, 0x5a, 0x9c, 0x90,
	0x50, 0x8f, 0xfc, 0x2a, 0xf3, 0x77, 0xe9, 0xfe, 0x36, 0x37, 0x51, 0xdf, 0x16, 0x5d, 0x5e, 0x74,
	0x1c, 0x12, 0x88, 0x95, 0x20, 0x42, 0x3d, 0x6c, 0xdf, 0x21, 0x59, 0x7b, 0x6c, 0x0e, 0x41, 0xed,
	0x1a, 0xd8, 0x92, 0xb1, 0x95, 0xac, 0x3f, 0xd7, 0xc8, 0x96, 0x18, 0x83, 0x60, 0x10, 0x27, 0x9c,
	0x33, 0x97, 0xf6, 0x7d, 0xb8, 0xf9, 0xb3, 0xe9, 0x73, 0x01, 0x71, 0xeb, 0x2e, 0xf9, 0x98, 0x37,
	0x52, 0x36, 0x3d, 0xce, 0x47, 0xae, 0xa6, 0x8f, 0xfc, 0x05, 0xa9, 0x95, 0xf5, 0xab, 0xed, 0x1c,
	0xf9, 0xf7, 0x97, 0xf9, 0x27, 0xdd, 0x5f, 0xdb, 0xad, 0xdd, 0xfd, 0xcb, 0x65, 0xbc, 0x8a, 0xec,
	0xd8, 0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x10, 0xc1, 0x48, 0xbf, 0x01, 0x00, 0x00,
}
