package main

//go:generate swagger generate spec -w ./web -o swagger.json --scan-models
//go:generate swagger mixin swagger.json api.yaml --output=swagger.json
//go:generate go run gen-openapi.go
// go:generate swagger serve swagger.json /flavor:redoc

import (
	"flag"
	"fmt"
	"io/ioutil"
	"os"
	"strings"
)

func main() {
	inputFile := flag.String("i", "swagger.json", "input file")
	outputFile := flag.String("o", "web/swagger.json.go", "output go file")
	flag.Parse()

	inputData, err := ioutil.ReadFile(*inputFile)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	var data []string
	for _, v := range inputData {
		data = append(data, fmt.Sprintf("%v", v))
	}

	out, err := os.Create(*outputFile)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	w(out, "// Code generated by gen-openapi.go")
	w(out, "// DO NOT EDIT!")
	w(out, "")
	w(out, "package web")
	w(out, "")
	w(out, "var swaggerJson = []byte{"+strings.Join(data, ",")+"}")
}

func w(out *os.File, s string) {
	_, err := out.Write([]byte(s + "\n"))
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
}
