// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// swagger:model
type EventLevel struct {
	// Идентификатор записи
	// required: true
	// example: 2
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Код
	// required: true
	// example: info
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Название
	// required: true
	// example: Информация
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Цвет
	// example: info-circle
	Color                string   `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventLevel) Reset()         { *m = EventLevel{} }
func (m *EventLevel) String() string { return proto.CompactTextString(m) }
func (*EventLevel) ProtoMessage()    {}
func (*EventLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *EventLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLevel.Unmarshal(m, b)
}
func (m *EventLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLevel.Marshal(b, m, deterministic)
}
func (m *EventLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLevel.Merge(m, src)
}
func (m *EventLevel) XXX_Size() int {
	return xxx_messageInfo_EventLevel.Size(m)
}
func (m *EventLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLevel.DiscardUnknown(m)
}

var xxx_messageInfo_EventLevel proto.InternalMessageInfo

func (m *EventLevel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventLevel) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EventLevel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventLevel) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

// swagger:model
type EventType struct {
	// Идентификатор записи
	// required: true
	// example: 2
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Код
	// required: true
	// example: info
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Название
	// required: true
	// example: Информация
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Цвет
	// example: info-circle
	Color string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	// Иконка
	// example: #d1c3e0
	Icon                 string   `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventType) Reset()         { *m = EventType{} }
func (m *EventType) String() string { return proto.CompactTextString(m) }
func (*EventType) ProtoMessage()    {}
func (*EventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *EventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventType.Unmarshal(m, b)
}
func (m *EventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventType.Marshal(b, m, deterministic)
}
func (m *EventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventType.Merge(m, src)
}
func (m *EventType) XXX_Size() int {
	return xxx_messageInfo_EventType.Size(m)
}
func (m *EventType) XXX_DiscardUnknown() {
	xxx_messageInfo_EventType.DiscardUnknown(m)
}

var xxx_messageInfo_EventType proto.InternalMessageInfo

func (m *EventType) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventType) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *EventType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EventType) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *EventType) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

// swagger:model
type EventLevelsResponse struct {
	// required: true
	Items                []*EventLevel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EventLevelsResponse) Reset()         { *m = EventLevelsResponse{} }
func (m *EventLevelsResponse) String() string { return proto.CompactTextString(m) }
func (*EventLevelsResponse) ProtoMessage()    {}
func (*EventLevelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *EventLevelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventLevelsResponse.Unmarshal(m, b)
}
func (m *EventLevelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventLevelsResponse.Marshal(b, m, deterministic)
}
func (m *EventLevelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLevelsResponse.Merge(m, src)
}
func (m *EventLevelsResponse) XXX_Size() int {
	return xxx_messageInfo_EventLevelsResponse.Size(m)
}
func (m *EventLevelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLevelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventLevelsResponse proto.InternalMessageInfo

func (m *EventLevelsResponse) GetItems() []*EventLevel {
	if m != nil {
		return m.Items
	}
	return nil
}

// swagger:model
type EventTypesResponse struct {
	// required: true
	Items                []*EventType `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EventTypesResponse) Reset()         { *m = EventTypesResponse{} }
func (m *EventTypesResponse) String() string { return proto.CompactTextString(m) }
func (*EventTypesResponse) ProtoMessage()    {}
func (*EventTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *EventTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventTypesResponse.Unmarshal(m, b)
}
func (m *EventTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventTypesResponse.Marshal(b, m, deterministic)
}
func (m *EventTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTypesResponse.Merge(m, src)
}
func (m *EventTypesResponse) XXX_Size() int {
	return xxx_messageInfo_EventTypesResponse.Size(m)
}
func (m *EventTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventTypesResponse proto.InternalMessageInfo

func (m *EventTypesResponse) GetItems() []*EventType {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*EventLevel)(nil), "api.EventLevel")
	proto.RegisterType((*EventType)(nil), "api.EventType")
	proto.RegisterType((*EmptyRequest)(nil), "api.EmptyRequest")
	proto.RegisterType((*EventLevelsResponse)(nil), "api.EventLevelsResponse")
	proto.RegisterType((*EventTypesResponse)(nil), "api.EventTypesResponse")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0xe2, 0x2c, 0x4f, 0x4d, 0x82,
	0xf0, 0x95, 0xa2, 0xb8, 0xb8, 0x5c, 0xcb, 0x52, 0xf3, 0x4a, 0x7c, 0x52, 0xcb, 0x52, 0x73, 0x84,
	0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84,
	0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c,
	0x90, 0x58, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0x33, 0x44, 0x0c, 0xc4, 0x16, 0x12, 0xe1, 0x62, 0x4d,
	0xce, 0xcf, 0xc9, 0x2f, 0x92, 0x60, 0x01, 0x0b, 0x42, 0x38, 0x4a, 0xb9, 0x5c, 0x9c, 0x60, 0xb3,
	0x43, 0x2a, 0x0b, 0x52, 0xa9, 0x6b, 0x34, 0x48, 0x65, 0x66, 0x72, 0x7e, 0x9e, 0x04, 0x2b, 0x44,
	0x25, 0x88, 0xad, 0xc4, 0xc7, 0xc5, 0xe3, 0x9a, 0x5b, 0x50, 0x52, 0x19, 0x94, 0x5a, 0x58, 0x9a,
	0x5a, 0x5c, 0xa2, 0x64, 0xc3, 0x25, 0x8c, 0xf0, 0x5a, 0x71, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0xaa, 0x90, 0x2a, 0x17, 0x6b, 0x66, 0x49, 0x6a, 0x6e, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xb7, 0x11, 0xbf, 0x1e, 0x28, 0x70, 0x10, 0x0a, 0x83, 0x20, 0xb2, 0x4a, 0x56, 0x5c, 0x42, 0x70,
	0xc7, 0x23, 0x34, 0xab, 0xa0, 0x6a, 0xe6, 0x43, 0x68, 0x06, 0xa9, 0x83, 0xea, 0x35, 0x9a, 0xc8,
	0x08, 0xd5, 0x5c, 0xec, 0x9c, 0x9f, 0x97, 0x96, 0x99, 0x5e, 0x5a, 0x94, 0x58, 0x92, 0x5f, 0x24,
	0x54, 0xcd, 0xc5, 0x8d, 0xe4, 0x20, 0x21, 0x41, 0x88, 0x66, 0x24, 0x27, 0x4b, 0x49, 0xa0, 0x39,
	0x06, 0x6e, 0xb1, 0x92, 0xfd, 0xa3, 0x25, 0x92, 0xd6, 0x5c, 0xbc, 0xfa, 0xa9, 0x20, 0xb9, 0xf8,
	0x1c, 0xb0, 0xa4, 0x95, 0xd6, 0x85, 0x85, 0x17, 0xf6, 0x5f, 0xd8, 0x71, 0xb1, 0xf1, 0xc2, 0xbe,
	0x0b, 0xbb, 0x14, 0x2e, 0x36, 0x5f, 0x6c, 0xb8, 0xb0, 0xef, 0xc2, 0xa6, 0x0b, 0x7b, 0x2f, 0x6c,
	0xbd, 0xb0, 0x53, 0x01, 0x2c, 0xba, 0xf1, 0x62, 0xf7, 0xc5, 0xa6, 0x0b, 0x3b, 0x2e, 0xec, 0x74,
	0x62, 0x8d, 0x02, 0x45, 0x7d, 0x12, 0x1b, 0x38, 0xda, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x40, 0x75, 0x76, 0x5d, 0x13, 0x02, 0x00, 0x00,
}
